### ISSUE TITLE
Cannot add metadata with x-amz-meta-*

### ISSUE THREAD

**Issue by worldlyjohn** [joonhocho/s3-policy-v4#1]
I'm not sure if it's just me, but I'm trying to add metadata with the upload, but I can't add arbitrary key/value pairs other than the ones you've defined.

How would you suggest I define x-amz-meta-\* ?

Thanks!

**Comment by joonhocho** [comment]
I merged a PR from @lerman that addresses this issue. Please take a look at the change!

**Comment by worldlyjohn** [comment]
👍
